insert into laboratories ("labId", "labName", address1, address2, "stateProvinceRegion", city, country, "zipPostal", "activeLab", "labTypes")
values  (1, 'BARC', '11 Napier Road', 'NULL', 'Richmond', 'Johannesburg', 'South Africa', '2092', 'TRUE', 'Mycobacteriology'),
        (2, 'BJMC', 'Third floor, Infosys Building, BJ. Govt. Medical College and Sassoon, ', 'Jai Prakash Narayan Road', 'Maharashtra', 'Pune', 'India', '411001', 'TRUE', 'Mycobacteriology'),
        (3, 'Blufstein', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (26, 'Carolinas Laboratory Network', '5400 Airport Center Parkway', 'Building H', 'NC', 'Charlotte', 'NULL', '28202', 'TRUE', 'Mycobacteriology'),
        (29, 'Arizona State Public Health Laboratory', 'NULL', 'NULL', 'AZ', 'Phoenix', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (33, 'Florida Department of Health, Bureau of Public Health Laboratories', 'NULL', 'NULL', 'FL', 'Jacksonville', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (4, 'Laboratorio Humberto Guerra Allison (Cayetano)', 'Universidad Peruana Cayetano Heredia', 'Av. Honorio Delgado 430. Urb Ingenieria', 'Lima', 'San Martin de Porres', 'Peru', '15102', 'TRUE', 'Mycobacteriology'),
        (5, 'CDC-Kisumu', 'KISIAN FIELD STATION, KEMRI/CDC PROGRAM KISUMU-BUSIA ROAD', 'OPPOSITE Kisan Primary School, P.O BOX 1578', 'Nyanza', 'Kisumu', 'Kenya', 'NULL', 'TRUE', 'Mycobacteriology'),
        (6, 'CLS', '4th Floor Spencer Lister Building NHLS Comple', 'De Korte street', 'Braamfontein', 'Johannesburg', 'South Africa', 'NULL', 'TRUE', 'Mycobacteriology'),
        (7, 'GHESKIO', 'Les Centres GHESKIO', '33, Bld. Harry Truman', 'NULL', 'Port-au-Prince', 'Haiti', 'NULL', 'TRUE', 'Mycobacteriology'),
        (8, 'Global Labs', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (9, 'Makerere', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (10, 'JCRC', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (11, 'KCMH', '104 Ratchadamri Road', 'Pathumwan', 'NULL', 'Bangkok', 'Thailand', 'NULL', 'TRUE', 'Mycobacteriology'),
        (12, 'Laboratorio de Bacteriologica e Bioensaios', 'Laboratorio de Pesquisa Clinica em DST/AIDS - LAPCLIN-AIDS', 'Fundacao Oswaldo Cruz - Instituto Nacional de Infectologia Evandro Cha', 'Manguinhos', 'Rio de Janeiro', 'Brazil', 'NULL', 'TRUE', 'Mycobacteriology'),
        (13, 'NRL', 'Hanoi Lung Hospital', '44 Thanh Nhan street', 'Hai Ba Trung', 'Hanoi', 'Vietnam', 'NULL', 'TRUE', 'Mycobacteriology'),
        (14, 'NY Public Health Laboratory', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (15, 'PHLS', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (16, 'RIHES', 'Research Institute for Health Sciences', '110 Intravaroros Road', 'NULL', 'Chang Mai', 'Thailand', 'NULL', 'TRUE', 'Mycobacteriology'),
        (17, 'Texas DSHS', '1100 W 49th street Lab sec.', 'NULL', 'Texas', 'Austin', 'NULL', '78756', 'TRUE', 'Mycobacteriology'),
        (18, 'UCSD', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (19, 'UNC Lilongwe', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (20, 'UZ-UCSF', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (21, 'YRG', 'VHS-YRG CARE Infectious Diseases Laboratory Admin. BLDG. II Floor', 'Voluntary Health Services Tidel Park Road', 'Tamil Nadu', 'Chennai', 'India', '600113', 'TRUE', 'Mycobacteriology'),
        (22, 'TN Department of Health, Laboratory Services', 'NULL', 'NULL', 'TN', 'Nashville', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (23, 'San Francisco Public Health Laboratory', '101 Grove Street', 'Room 419', 'CA', 'San Francisco', 'USA', '94102', 'TRUE', 'Mycobacteriology'),
        (24, 'Pathology and Laboratory Services at Denver Health Medical Center', 'NULL', 'NULL', 'CO', 'Denver', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (27, 'Georgia Public Health Lab', '1749 Clairmont Road', 'NULL', 'GA', 'Decatur', 'NULL', '30333', 'TRUE', 'Mycobacteriology'),
        (28, 'Diagnostic Laboratory Services', '99-859 Iwaiwa Street', 'NULL', 'Hawaii', 'Aiea', 'NULL', '96701', 'TRUE', 'Mycobacteriology'),
        (30, 'Maricopa County Department of Public Health Laboratory', 'NULL', 'NULL', 'AZ', 'Phoenix', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (31, 'Maryland State TB Lab', 'NULL', 'NULL', 'MD', 'Baltimore', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (32, 'Public Health-Seattle & King County Laboratory', 'NULL', 'NULL', 'WA', 'Seattle', 'NULL', 'NULL', 'TRUE', 'Mycobacteriology'),
        (34, 'Alberta Provincial Lab', 'NULL', 'NULL', 'Alberta', 'NULL', 'Canada', 'NULL', 'TRUE', 'Mycobacteriology'),
        (35, 'Provincial laboratory for Ontario (PHOL)', 'NULL', 'NULL', 'NULL', 'NULL', 'Canada', 'NULL', 'TRUE', 'Mycobacteriology'),
        (37, 'BCCDC Public Health Laboratory', 'NULL', 'NULL', 'NULL', 'NULL', 'Canada', 'NULL', 'TRUE', 'Mycobacteriology'),
        (25, 'North Carolina State Laboratory of Public Health', 'NULL', 'NULL', 'NC', 'Raleigh', 'NULL', 'NULL', 'TRUE', 'Hematology');